### ISSUE TITLE
How to not use this library when in production mode?

### ISSUE THREAD

**Issue by hamza-farooq-astutesol** [sunilsharma08/XNLogger#62]
Hi there,

First of all, great work. Really impressive.

The issue I am currently having is that I don't want to show the logging UI when in Production mode. How to achieve that?
I used stopLogging function but it only stop the library from logging purpose but it still appears the Logging UI.
I do not want to remove this library and install again and again when switching between production mode and development mode. Thank you.

Best Regards

**Comment by sunilsharma08** [comment]
Hi,

If your are using cocoa pods then try ```pod 'XNLogger', :configurations => ['Debug']```
This will integrate library only for debug build and lib will be eliminated from production build.

Another way to avoid showing XNLogger UI is ```XNUIManager.shared.startGesture = .none```
and call ```XNLogger.shared.stopLogging()``` to stop logging.

Hope this resolve your issue.

**Comment by hamza-farooq-astutesol** [comment]
Yes it worked. Thank you very much.
